#name : Mi primer github action
name: papeline para revisar archivo

on:
 push: 
  branches: [main]

jobs:
 saludo:
  runs-on: ubuntu-latest
  
 # steps:
  # - name: mostrar mensaje
  #   run: echo "Hola, este es mi primer mensaje"
  # - name: fallo intencionado
   #  run: exi 1
   #dbhsbjs

  steps:
    - name: checkout del codigo
      uses: actions/checkout@v4
    - name: usar NODE.JS
      uses: actions/setup-node@v4
      with:
      node-version: '20'
    - name: construir app con node
      run: npm install
    - name: verificar si app.js existe
      run: |
        if [ ! -f " SGITHUB_WORKSPACE/app.js" ]; then
          echo "No se encontro el archivo app.js en la raiz"
          exit 1
        fi
        echo "Archivo app.js encontrado, continuando con el workflow..."
  
     